In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('round.csv')

In [3]:
data['c2_familiarity_r1'].fillna((data['c2_familiarity_r1'].mean()), inplace=True)
data['c2_familiarity_r2'].fillna((data['c2_familiarity_r2'].mean()), inplace=True)
data['c2_familiarity_r3'].fillna((data['c2_familiarity_r3'].mean()), inplace=True)

In [4]:
data = data[['second_rating','like_avg','c1_familiarity_r1','c1_familiarity_r2','c1_familiarity_r3','c2_familiarity_r1','c2_familiarity_r2','c2_familiarity_r3','surprise_avg']] 
data

,second_rating,like_avg,c1_familiarity_r1,c1_familiarity_r2,c1_familiarity_r3,c2_familiarity_r1,c2_familiarity_r2,c2_familiarity_r3,surprise_avg
0,45,3.00,4,4,4,3.062344,3.099751,3.01995,2.330000
1,82,4.00,5,2,5,3.062344,3.099751,3.01995,4.666667
2,19,4.33,2,1,3,3.062344,3.099751,3.01995,3.666667
3,7,2.33,4,2,4,3.062344,3.099751,3.01995,1.000000
4,9,4.00,1,4,3,3.062344,3.099751,3.01995,2.333333
5,14,3.67,1,1,3,3.062344,3.099751,3.01995,2.333333
6,31,4.00,1,2,3,3.062344,3.099751,3.01995,4.333333
7,22,3.33,2,4,4,3.062344,3.099751,3.01995,1.333333
8,4,4.33,3,5,4,3.062344,3.099751,3.01995,2.333333
9,16,3.33,4,4,2,3.062344,3.099751,3.01995,1.666667
10,23,3.33,4,5,2,3.062344,3.099751,3.01995,3.666667
11,14,3.33,1,2,4,3.062344,3.099751,3.01995,2.000000
12,35,4.00,1,4,4,3.062344,3.099751,3.01995,4.000000
13,24,4.33,3,4,4,3.062344,3.099751,3.01995,3.666667
14,32,4.00,4,5,3,3.062344,3.099751,3.01995,4.000000
15,15,4.00,5,4,5,3.062344,3.099751,3.01995,2.666667
16,18,3.33,2,4,5,3.062344,3.099751,3.01995,2.000000
17,17,3.67,4,5,4,3.062344,3.099751,3.01995,3.000000
18,23,4.33,4,4,1,3.062344,3.099751,3.01995,2.333333
19,42,4.33,1,2,3,3.062344,3.099751,3.01995,2.666667
20,31,4.00,4,4,4,3.062344,3.099751,3.01995,3.000000
21,24,3.33,2,4,3,3.062344,3.099751,3.01995,1.333333
22,10,3.33,4,3,2,3.062344,3.099751,3.01995,3.333333
23,39,3.33,2,5,4,3.062344,3.099751,3.01995,3.000000
24,20,3.33,4,4,2,3.062344,3.099751,3.01995,3.000000
25,22,4.00,3,3,4,3.062344,3.099751,3.01995,4.000000
26,24,4.33,3,3,4,3.062344,3.099751,3.01995,4.333333
27,41,4.67,3,4,4,3.062344,3.099751,3.01995,4.333333
28,20,4.67,2,3,3,3.062344,3.099751,3.01995,3.000000
29,38,4.00,4,4,5,3.062344,3.099751,3.01995,3.666667
...,...,...,...,...,...,...,...,...,...
470,39,4.33,5,4,3,4.000000,2.000000,3.00000,4.000000
471,32,3.33,1,3,2,1.000000,3.000000,2.00000,4.000000
472,41,3.33,4,3,5,4.000000,3.000000,2.00000,2.333333
473,19,4.00,4,3,5,2.000000,4.000000,2.00000,3.666667
474,22,2.67,5,3,3,4.000000,5.000000,5.00000,1.666667
475,31,3.33,1,2,3,3.000000,5.000000,3.00000,3.000000
476,84,3.67,1,5,2,1.000000,1.000000,1.00000,2.666667
477,26,3.67,4,3,4,4.000000,2.000000,2.00000,2.666667
478,20,3.33,2,1,3,5.000000,4.000000,3.00000,3.000000
479,29,3.67,3,4,1,3.000000,4.000000,1.00000,4.333333
480,16,3.33,2,4,1,2.000000,3.000000,2.00000,3.666667
481,17,2.67,1,3,2,3.000000,4.000000,5.00000,2.666667
482,30,3.67,3,5,2,3.000000,2.000000,2.00000,3.000000
483,39,4.00,4,3,1,3.000000,3.000000,1.00000,3.666667
484,33,2.67,3,5,4,3.000000,4.000000,3.00000,2.333333
485,39,2.67,3,4,3,3.000000,4.000000,3.00000,2.333333
486,41,3.00,3,3,3,3.000000,3.000000,2.00000,2.333333
487,5,2.33,3,3,1,1.000000,5.000000,1.00000,1.666667
488,29,2.00,3,3,1,2.000000,3.000000,1.00000,2.666667
489,26,4.33,4,4,3,3.000000,3.000000,4.00000,3.666667
490,9,4.00,5,2,2,5.000000,4.000000,4.00000,4.333333
491,52,2.67,4,4,4,3.000000,3.000000,3.00000,3.000000
492,30,4.33,2,4,3,3.000000,4.000000,4.00000,3.000000
493,19,3.67,3,3,4,3.000000,2.000000,3.00000,3.333333
494,38,3.67,5,5,4,3.062344,3.099751,3.01995,3.333333
495,32,3.67,5,4,4,3.062344,3.099751,3.01995,2.666667
496,24,3.67,4,4,3,3.062344,3.099751,3.01995,1.333333
497,58,4.33,4,4,4,3.062344,3.099751,3.01995,3.666667
498,37,3.67,4,4,2,3.062344,3.099751,3.01995,3.000000
499,23,2.67,4,4,4,3.062344,3.099751,3.01995,3.666667

In [5]:
data["target"]= data["surprise_avg"].apply(lambda x: 0 if x < 3 else 1  )
data

,second_rating,like_avg,c1_familiarity_r1,c1_familiarity_r2,c1_familiarity_r3,c2_familiarity_r1,c2_familiarity_r2,c2_familiarity_r3,surprise_avg,target
0,45,3.00,4,4,4,3.062344,3.099751,3.01995,2.330000,0
1,82,4.00,5,2,5,3.062344,3.099751,3.01995,4.666667,1
2,19,4.33,2,1,3,3.062344,3.099751,3.01995,3.666667,1
3,7,2.33,4,2,4,3.062344,3.099751,3.01995,1.000000,0
4,9,4.00,1,4,3,3.062344,3.099751,3.01995,2.333333,0
5,14,3.67,1,1,3,3.062344,3.099751,3.01995,2.333333,0
6,31,4.00,1,2,3,3.062344,3.099751,3.01995,4.333333,1
7,22,3.33,2,4,4,3.062344,3.099751,3.01995,1.333333,0
8,4,4.33,3,5,4,3.062344,3.099751,3.01995,2.333333,0
9,16,3.33,4,4,2,3.062344,3.099751,3.01995,1.666667,0
10,23,3.33,4,5,2,3.062344,3.099751,3.01995,3.666667,1
11,14,3.33,1,2,4,3.062344,3.099751,3.01995,2.000000,0
12,35,4.00,1,4,4,3.062344,3.099751,3.01995,4.000000,1
13,24,4.33,3,4,4,3.062344,3.099751,3.01995,3.666667,1
14,32,4.00,4,5,3,3.062344,3.099751,3.01995,4.000000,1
15,15,4.00,5,4,5,3.062344,3.099751,3.01995,2.666667,0
16,18,3.33,2,4,5,3.062344,3.099751,3.01995,2.000000,0
17,17,3.67,4,5,4,3.062344,3.099751,3.01995,3.000000,1
18,23,4.33,4,4,1,3.062344,3.099751,3.01995,2.333333,0
19,42,4.33,1,2,3,3.062344,3.099751,3.01995,2.666667,0
20,31,4.00,4,4,4,3.062344,3.099751,3.01995,3.000000,1
21,24,3.33,2,4,3,3.062344,3.099751,3.01995,1.333333,0
22,10,3.33,4,3,2,3.062344,3.099751,3.01995,3.333333,1
23,39,3.33,2,5,4,3.062344,3.099751,3.01995,3.000000,1
24,20,3.33,4,4,2,3.062344,3.099751,3.01995,3.000000,1
25,22,4.00,3,3,4,3.062344,3.099751,3.01995,4.000000,1
26,24,4.33,3,3,4,3.062344,3.099751,3.01995,4.333333,1
27,41,4.67,3,4,4,3.062344,3.099751,3.01995,4.333333,1
28,20,4.67,2,3,3,3.062344,3.099751,3.01995,3.000000,1
29,38,4.00,4,4,5,3.062344,3.099751,3.01995,3.666667,1
...,...,...,...,...,...,...,...,...,...,...
470,39,4.33,5,4,3,4.000000,2.000000,3.00000,4.000000,1
471,32,3.33,1,3,2,1.000000,3.000000,2.00000,4.000000,1
472,41,3.33,4,3,5,4.000000,3.000000,2.00000,2.333333,0
473,19,4.00,4,3,5,2.000000,4.000000,2.00000,3.666667,1
474,22,2.67,5,3,3,4.000000,5.000000,5.00000,1.666667,0
475,31,3.33,1,2,3,3.000000,5.000000,3.00000,3.000000,1
476,84,3.67,1,5,2,1.000000,1.000000,1.00000,2.666667,0
477,26,3.67,4,3,4,4.000000,2.000000,2.00000,2.666667,0
478,20,3.33,2,1,3,5.000000,4.000000,3.00000,3.000000,1
479,29,3.67,3,4,1,3.000000,4.000000,1.00000,4.333333,1
480,16,3.33,2,4,1,2.000000,3.000000,2.00000,3.666667,1
481,17,2.67,1,3,2,3.000000,4.000000,5.00000,2.666667,0
482,30,3.67,3,5,2,3.000000,2.000000,2.00000,3.000000,1
483,39,4.00,4,3,1,3.000000,3.000000,1.00000,3.666667,1
484,33,2.67,3,5,4,3.000000,4.000000,3.00000,2.333333,0
485,39,2.67,3,4,3,3.000000,4.000000,3.00000,2.333333,0
486,41,3.00,3,3,3,3.000000,3.000000,2.00000,2.333333,0
487,5,2.33,3,3,1,1.000000,5.000000,1.00000,1.666667,0
488,29,2.00,3,3,1,2.000000,3.000000,1.00000,2.666667,0
489,26,4.33,4,4,3,3.000000,3.000000,4.00000,3.666667,1
490,9,4.00,5,2,2,5.000000,4.000000,4.00000,4.333333,1
491,52,2.67,4,4,4,3.000000,3.000000,3.00000,3.000000,1
492,30,4.33,2,4,3,3.000000,4.000000,4.00000,3.000000,1
493,19,3.67,3,3,4,3.000000,2.000000,3.00000,3.333333,1
494,38,3.67,5,5,4,3.062344,3.099751,3.01995,3.333333,1
495,32,3.67,5,4,4,3.062344,3.099751,3.01995,2.666667,0
496,24,3.67,4,4,3,3.062344,3.099751,3.01995,1.333333,0
497,58,4.33,4,4,4,3.062344,3.099751,3.01995,3.666667,1
498,37,3.67,4,4,2,3.062344,3.099751,3.01995,3.000000,1
499,23,2.67,4,4,4,3.062344,3.099751,3.01995,3.666667,1

In [6]:
X_train, X_test, y_train, y_test = train_test_split(data.drop(['surprise_avg','target'],axis=1), 
                                                    data['target'], test_size=0.30, 
                                                    random_state=101)

In [7]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.56      0.52      0.54        69
          1       0.62      0.65      0.63        81

avg / total       0.59      0.59      0.59       150